version: '3.9'
services:
  metabase-secrets:
    image: metabase/metabase:latest
    container_name: metabase-secrets
    hostname: metabase-secrets
    volumes:
      - ./metabase-data:/metabase-data
      - ./master_postulation_prj:/metabase-db
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: admin
      MB_DB_PASS: admin
      MB_DB_HOST: postgres-secrets
    networks:
      - metanet1-secrets
    depends_on:
      - postgres-secrets
  postgres-secrets:
    image: postgres:latest
    container_name: postgres-secrets
    hostname: postgres-secrets
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    networks:
      - metanet1-secrets
    volumes:
      - ./pgdata:/var/lib/postgresql/data
networks:
  metanet1-secrets:
    driver: bridge